

import "./globals.css";
import Navbar from "@/components/Navbar";




export const metadata = {
  title: "Hunting Coder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body >
       <Navbar/>
        {children}  
      </body>
    </html>
  );
}
